/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SklepRouteImport } from './routes/sklep'
import { Route as TeoriaRouteImport } from './routes/teoria'
import { Route as EgzaminExamIdRouteImport } from './routes/egzamin.$examId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SklepRoute = SklepRouteImport.update({
  id: '/sklep',
  path: '/sklep',
  getParentRoute: () => rootRouteImport,
} as any)
const TeoriaRoute = TeoriaRouteImport.update({
  id: '/teoria',
  path: '/teoria',
  getParentRoute: () => rootRouteImport,
} as any)
const EgzaminExamIdRoute = EgzaminExamIdRouteImport.update({
  id: '/egzamin/$examId',
  path: '/egzamin/$examId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sklep': typeof SklepRoute
  '/teoria': typeof TeoriaRoute
  '/egzamin/$examId': typeof EgzaminExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sklep': typeof SklepRoute
  '/teoria': typeof TeoriaRoute
  '/egzamin/$examId': typeof EgzaminExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sklep': typeof SklepRoute
  '/teoria': typeof TeoriaRoute
  '/egzamin/$examId': typeof EgzaminExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sklep' | '/teoria' | '/egzamin/$examId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sklep' | '/teoria' | '/egzamin/$examId'
  id: '__root__' | '/' | '/sklep' | '/teoria' | '/egzamin/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SklepRoute: typeof SklepRoute
  TeoriaRoute: typeof TeoriaRoute
  EgzaminExamIdRoute: typeof EgzaminExamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sklep': {
      id: '/sklep'
      path: '/sklep'
      fullPath: '/sklep'
      preLoaderRoute: typeof SklepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teoria': {
      id: '/teoria'
      path: '/teoria'
      fullPath: '/teoria'
      preLoaderRoute: typeof TeoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egzamin/$examId': {
      id: '/egzamin/$examId'
      path: '/egzamin/$examId'
      fullPath: '/egzamin/$examId'
      preLoaderRoute: typeof EgzaminExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SklepRoute: SklepRoute,
  TeoriaRoute: TeoriaRoute,
  EgzaminExamIdRoute: EgzaminExamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
