/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EgzaminExamIdRouteImport } from './routes/egzamin.$examId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EgzaminExamIdRoute = EgzaminExamIdRouteImport.update({
  id: '/egzamin/$examId',
  path: '/egzamin/$examId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/egzamin/$examId': typeof EgzaminExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/egzamin/$examId': typeof EgzaminExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/egzamin/$examId': typeof EgzaminExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/egzamin/$examId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/egzamin/$examId'
  id: '__root__' | '/' | '/egzamin/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EgzaminExamIdRoute: typeof EgzaminExamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egzamin/$examId': {
      id: '/egzamin/$examId'
      path: '/egzamin/$examId'
      fullPath: '/egzamin/$examId'
      preLoaderRoute: typeof EgzaminExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EgzaminExamIdRoute: EgzaminExamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
